<h2>Exercise 02. Join</h2>

In [22]:
import pandas as pd
import sqlite3

### 1. Create a connection to the database using the sqlite3 library.

In [23]:
conn = sqlite3.connect("../data/checking-logs.sqlite")

### 2. Create a new table called datamart in the database by joining the tables pageviews and checker using only one query.

In [24]:
datamart = pd.io.sql.read_sql("""
SELECT
    c.uid,
    c.labname,
    c.timestamp AS first_commit_ts,
    pv.first_view_ts
FROM checker c
LEFT JOIN (
    SELECT uid, MIN(datetime) AS first_view_ts
    FROM pageviews
    GROUP BY uid
) pv
ON c.uid = pv.uid
WHERE c.status = 'ready'
AND c.numTrials = 1
AND c.labname IN ('laba04','laba04s','laba05','laba06','laba06s','project1')
AND c.uid LIKE 'user_%';
""",
conn,
parse_dates = ['first_commit_ts', 'first_view_ts'])

datamart.info()

<class 'pandas.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   uid              140 non-null    str
 1   labname          140 non-null    str
 2   first_commit_ts  140 non-null    datetime64[us]
 3   first_view_ts    59 non-null     datetime64[us]
dtypes: datetime64[us](2), str(2)
memory usage: 4.5 KB

### 3. Using Pandas methods, create two dataframes: test and control.

In [25]:
datamart

         uid   labname            first_commit_ts              first_view_ts
0     user_4  project1 2020-04-17 05:19:02.744528                        NaT
1     user_4    laba04 2020-04-17 11:33:17.366400                        NaT
2     user_4   laba04s 2020-04-17 11:48:41.992466                        NaT
3    user_17  project1 2020-04-18 07:56:45.408648 2020-04-18 10:56:55.833899
4    user_30    laba04 2020-04-18 13:36:53.971502 2020-04-17 22:46:26.785035
..       ...       ...                        ...                        ...
135  user_23    laba06 2020-05-21 08:34:10.517205                        NaT
136  user_19   laba06s 2020-05-21 13:27:06.705881 2020-04-21 20:30:38.034966
137  user_23   laba06s 2020-05-21 14:29:15.709568                        NaT
138  user_17    laba06 2020-05-21 15:21:31.567615 2020-04-18 10:56:55.833899
139  user_17   laba06s 2020-05-21 17:39:17.783615 2020-04-18 10:56:55.833899

[140 rows x 4 columns]

In [26]:
test = datamart[datamart["first_view_ts"].notna()].copy()
control = datamart[datamart["first_view_ts"].isna()].copy()

In [27]:
test

         uid   labname            first_commit_ts              first_view_ts
3    user_17  project1 2020-04-18 07:56:45.408648 2020-04-18 10:56:55.833899
4    user_30    laba04 2020-04-18 13:36:53.971502 2020-04-17 22:46:26.785035
7    user_30   laba04s 2020-04-18 14:51:37.498399 2020-04-17 22:46:26.785035
8    user_14    laba04 2020-04-18 15:14:00.312338 2020-04-18 10:53:52.623447
11   user_14   laba04s 2020-04-18 22:30:30.247628 2020-04-18 10:53:52.623447
18   user_19    laba04 2020-04-20 19:05:01.297780 2020-04-21 20:30:38.034966
19   user_25    laba04 2020-04-20 19:16:50.673054 2020-05-09 23:54:54.260791
20   user_21    laba04 2020-04-21 17:48:00.487806 2020-04-22 22:40:36.824081
21   user_30  project1 2020-04-22 12:36:24.053518 2020-04-17 22:46:26.785035
23   user_21   laba04s 2020-04-22 20:09:21.857747 2020-04-22 22:40:36.824081
24   user_28    laba04 2020-04-22 21:47:19.707242 2020-05-10 21:07:50.350946
27   user_17    laba04 2020-04-23 14:24:29.947554 2020-04-18 10:56:55.833899
28    user_3    laba04 2020-04-23 20:29:14.054364 2020-05-08 10:53:47.123832
29    user_3   laba04s 2020-04-23 20:40:26.883591 2020-05-08 10:53:47.123832
33   user_10    laba04 2020-04-25 08:24:52.696624 2020-04-18 12:19:50.182714
34   user_10   laba04s 2020-04-25 08:37:54.604222 2020-04-18 12:19:50.182714
35   user_17   laba04s 2020-04-25 12:10:56.414175 2020-04-18 10:56:55.833899
41   user_28   laba04s 2020-04-26 15:53:44.906136 2020-05-10 21:07:50.350946
43    user_1    laba04 2020-04-26 17:06:18.462708 2020-04-26 21:53:59.624136
44    user_1   laba04s 2020-04-26 17:12:11.843671 2020-04-26 21:53:59.624136
46   user_18    laba04 2020-04-26 19:48:11.822365 2020-04-26 22:49:29.243278
47   user_18   laba04s 2020-04-26 20:03:56.935458 2020-04-26 22:49:29.243278
49   user_25   laba04s 2020-04-26 21:07:56.952117 2020-05-09 23:54:54.260791
54   user_14    laba05 2020-04-30 11:33:04.523118 2020-04-18 10:53:52.623447
57    user_3    laba05 2020-05-01 11:29:17.988118 2020-05-08 10:53:47.123832
58   user_25    laba05 2020-05-01 13:02:27.357650 2020-05-09 23:54:54.260791
60   user_28    laba05 2020-05-01 18:29:11.968537 2020-05-10 21:07:50.350946
61   user_10    laba05 2020-05-01 19:27:26.063245 2020-04-18 12:19:50.182714
62   user_30    laba05 2020-05-01 19:31:18.375833 2020-04-17 22:46:26.785035
64   user_17    laba05 2020-05-02 13:21:24.045876 2020-04-18 10:56:55.833899
66   user_21    laba05 2020-05-02 14:05:40.013959 2020-04-22 22:40:36.824081
68   user_19    laba05 2020-05-02 15:16:13.586405 2020-04-21 20:30:38.034966
70    user_1    laba05 2020-05-02 19:15:18.540185 2020-04-26 21:53:59.624136
76   user_18    laba05 2020-05-03 13:01:34.848756 2020-04-26 22:49:29.243278
83   user_14  project1 2020-05-05 21:35:43.554986 2020-04-18 10:53:52.623447
85    user_3  project1 2020-05-07 21:02:52.885133 2020-05-08 10:53:47.123832
86   user_25  project1 2020-05-08 11:10:28.100852 2020-05-09 23:54:54.260791
88   user_21  project1 2020-05-10 15:21:05.442755 2020-04-22 22:40:36.824081
89   user_18  project1 2020-05-11 10:10:04.166881 2020-04-26 22:49:29.243278
93   user_28  project1 2020-05-12 14:42:19.166414 2020-05-10 21:07:50.350946
95   user_10  project1 2020-05-12 20:12:28.056618 2020-04-18 12:19:50.182714
98   user_19  project1 2020-05-14 10:33:45.495389 2020-04-21 20:30:38.034966
103   user_1  project1 2020-05-14 20:56:08.898880 2020-04-26 21:53:59.624136
107   user_3    laba06 2020-05-17 09:56:40.480319 2020-05-08 10:53:47.123832
109   user_1    laba06 2020-05-17 16:26:35.268534 2020-04-26 21:53:59.624136
110  user_28    laba06 2020-05-17 17:08:48.257050 2020-05-10 21:07:50.350946
115  user_25    laba06 2020-05-18 17:07:47.988807 2020-05-09 23:54:54.260791
120   user_3   laba06s 2020-05-19 08:42:50.851878 2020-05-08 10:53:47.123832
123  user_19    laba06 2020-05-19 10:25:54.121465 2020-04-21 20:30:38.034966
124  user_10    laba06 2020-05-19 11:39:28.885637 2020-04-18 12:19:50.182714
127  user_30    laba06 2020-05-19 17:53:15.088248 2020-04-17 22:46:26.785035
128  user_21    laba06 2020-05-19 19:30:14.644328 2020-04-22 22:40:36.824081
129  user_10   laba06s 2020-05-20 07:37:31.175817 2020-04-18 12:19:50.182714
130   user_1   laba06s 2020-05-20 12:23:37.289724 2020-04-26 21:53:59.624136
131  user_25   laba06s 2020-05-20 14:02:26.512032 2020-05-09 23:54:54.260791
133  user_28   laba06s 2020-05-20 20:42:44.423160 2020-05-10 21:07:50.350946
136  user_19   laba06s 2020-05-21 13:27:06.705881 2020-04-21 20:30:38.034966
138  user_17    laba06 2020-05-21 15:21:31.567615 2020-04-18 10:56:55.833899
139  user_17   laba06s 2020-05-21 17:39:17.783615 2020-04-18 10:56:55.833899

In [28]:
control

         uid   labname            first_commit_ts first_view_ts
0     user_4  project1 2020-04-17 05:19:02.744528           NaT
1     user_4    laba04 2020-04-17 11:33:17.366400           NaT
2     user_4   laba04s 2020-04-17 11:48:41.992466           NaT
5     user_2    laba04 2020-04-18 13:42:35.482008           NaT
6     user_2   laba04s 2020-04-18 13:51:22.291271           NaT
..       ...       ...                        ...           ...
126   user_2   laba06s 2020-05-19 14:45:03.908268           NaT
132   user_6   laba06s 2020-05-20 14:50:07.609937           NaT
134   user_7   laba06s 2020-05-20 23:05:37.742597           NaT
135  user_23    laba06 2020-05-21 08:34:10.517205           NaT
137  user_23   laba06s 2020-05-21 14:29:15.709568           NaT

[81 rows x 4 columns]

In [29]:
mean_ts = test['first_view_ts'].mean()
control.fillna(mean_ts, inplace=True)

mean_ts

Timestamp('2020-04-27 00:40:05.761783')

In [30]:
control["first_view_ts"] = control["first_view_ts"].fillna(mean_ts)
control

         uid   labname            first_commit_ts              first_view_ts
0     user_4  project1 2020-04-17 05:19:02.744528 2020-04-27 00:40:05.761783
1     user_4    laba04 2020-04-17 11:33:17.366400 2020-04-27 00:40:05.761783
2     user_4   laba04s 2020-04-17 11:48:41.992466 2020-04-27 00:40:05.761783
5     user_2    laba04 2020-04-18 13:42:35.482008 2020-04-27 00:40:05.761783
6     user_2   laba04s 2020-04-18 13:51:22.291271 2020-04-27 00:40:05.761783
..       ...       ...                        ...                        ...
126   user_2   laba06s 2020-05-19 14:45:03.908268 2020-04-27 00:40:05.761783
132   user_6   laba06s 2020-05-20 14:50:07.609937 2020-04-27 00:40:05.761783
134   user_7   laba06s 2020-05-20 23:05:37.742597 2020-04-27 00:40:05.761783
135  user_23    laba06 2020-05-21 08:34:10.517205 2020-04-27 00:40:05.761783
137  user_23   laba06s 2020-05-21 14:29:15.709568 2020-04-27 00:40:05.761783

[81 rows x 4 columns]

In [31]:
test.to_sql("test", conn, if_exists="replace", index=False)
control.to_sql("control", conn, if_exists="replace", index=False)

81

In [32]:
control.info()

<class 'pandas.DataFrame'>
Index: 81 entries, 0 to 137
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   uid              81 non-null     str
 1   labname          81 non-null     str
 2   first_commit_ts  81 non-null     datetime64[us]
 3   first_view_ts    81 non-null     datetime64[us]
dtypes: datetime64[us](2), str(2)
memory usage: 3.2 KB

In [33]:
conn.close()